name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Criar ou atualizar branch gh-pages
      run: |
        git checkout -B gh-pages
        git reset --hard origin/main
        git clean -fd

    - name: Adicionar arquivos e fazer commit
      run: |
        git add index.html
        git commit -m "Deploy para GitHub Pages" || echo "Nada para commitar"

    - name: Enviar para a branch gh-pages
      run: |
        git push --force --set-upstream origin gh-pages
